
#ifndef _CORE_TWEEKSUBJECT_IDEL_H__
#define _CORE_TWEEKSUBJECT_IDEL_H__

#include "tweek/idl/Subject.idl"

module Veda
{  
  typedef string string_var;

	interface TweekSubject : tweek::Subject
	{		
		void setCommand( in string key, in string value );    
	};
};

#endif 