
#------Find osg Library----------------
SET( OSG_INC_DIR $ENV{OSG_INC_DIR} )

IF( CMAKE_BUILD_TYPE STREQUAL "Debug" )
 FIND_LIBRARY( OSG_LIB_DEBUG NAMES osgd PATHS $ENV{OSG_LIB_DIR} )
 SET( OSG_LIB ${OSG_LIB_DEBUG} )
ELSE( CMAKE_BUILD_TYPE STREQUAL "Release" )
 FIND_LIBRARY( OSG_LIB_RELEASE NAMES osg PATHS $ENV{OSG_LIB_DIR} )
 SET( OSG_LIB ${OSG_LIB_DEBUG} )
ENDIF( CMAKE_BUILD_TYPE STREQUAL "Debug" )


#------Find osgDB Library--------------
FIND_LIBRARY( OSGDB_LIB_DEBUG osgDBd $ENV{OSG_LIB_DIR} )


FIND_LIBRARY( OSGDB_LIB_RELEASE osgDB $ENV{OSG_LIB_DIR} )

set( OSGDB_LIB 
     debug OSGDB_LIB_DEBUG 
     optimized OSGDB_LIB_RELEASE
)

#------Find osgUtil Library------------
FIND_LIBRARY( OSGUTIL_LIB_DEBUG osgUtild $ENV{OSG_LIB_DIR} )

FIND_LIBRARY( OSGUTIL_LIB_RELEASE osgUtil $ENV{OSG_LIB_DIR} )

set( OSGUTIL_LIB 
     debug OSGUTIL_LIB_DEBUG 
     optimized OSGUTIL_LIB_RELEASE
)

#------Find osgFX Library--------------
FIND_LIBRARY( OSGFX_LIB_DEBUG osgFXd $ENV{OSG_LIB_DIR} )

FIND_LIBRARY( OSGFX_LIB_RELEASE osgFX $ENV{OSG_LIB_DIR} )

set( OSGFX_LIB 
     debug OSGFX_LIB_DEBUG 
     optimized OSGFX_LIB_RELEASE
)

