

#------Set osg include and library paths.
SET( OSG_INC_DIR $ENV{OSG_INC_DIR} )
SET( OSG_LIB_DIR $ENV{OSG_LIB_DIR} )


#------Set names for the osg library. 
SET( OSG_LIB_NAME osg )
SET( OSG_DB_LIB_NAME osgDB )
SET( OSG_UTIL_LIB_NAME osgUtil )
SET( OSG_FX_LIB_NAME osgFX )


#------Find library based on build type. 
IF( CMAKE_BUILD_TYPE STREQUAL "Debug" )
 FIND_LIBRARY( OPENSCENEGRAPH_OSG_LIB "${OSG_LIB_NAME}${CMAKE_DEBUG_POSTFIX}" PATHS ${OSG_LIB_DIR} )
 FIND_LIBRARY( OPENSCENEGRAPH_OSG_DB_LIB "${OSG_DB_LIB_NAME}${CMAKE_DEBUG_POSTFIX}" PATHS $ENV{OSG_LIB_DIR} )
 FIND_LIBRARY( OPENSCENEGRAPH_OSG_UTIL_LIB "${OSG_UTIL_LIB_NAME}${CMAKE_DEBUG_POSTFIX}" PATHS $ENV{OSG_LIB_DIR} )
 FIND_LIBRARY( OPENSCENEGRAPH_OSG_FX_LIB "${OSG_FX_LIB_NAME}${CMAKE_DEBUG_POSTFIX}" PATHS $ENV{OSG_LIB_DIR} ) 
ELSE( CMAKE_BUILD_TYPE STREQUAL "Release" )
 FIND_LIBRARY( OPENSCENEGRAPH_OSG_LIB "${OSG_LIB_NAME}" PATHS $ENV{OSG_LIB_DIR} )
 FIND_LIBRARY( OPENSCENEGRAPH_OSG_DB_LIB "${OSG_DB_LIB_NAME}" PATHS $ENV{OSG_LIB_DIR} )
 FIND_LIBRARY( OPENSCENEGRAPH_OSG_UTIL_LIB "${OSG_UTIL_LIB_NAME}" PATHS $ENV{OSG_LIB_DIR} )
 FIND_LIBRARY( OPENSCENEGRAPH_OSG_FX_LIB "${OSG_DB_LIB_NAME}" PATHS $ENV{OSG_LIB_DIR} ) 
ENDIF( CMAKE_BUILD_TYPE STREQUAL "Debug" )


