

#------Set osg include and library paths.
SET( OSG_INC_DIR $ENV{OSG_INC_DIR} )
SET( OSG_LIB_DIR $ENV{OSG_LIB_DIR} )


#------Set names for the osg library. 
SET( OSG_LIB_NAME osg )
SET( OSGDB_LIB_NAME osgDB )
SET( OSGUTIL_LIB_NAME osgUtil )
SET( OSGFX_LIB_NAME osgFX )


#------Find library based on build type. 
IF( CMAKE_BUILD_TYPE STREQUAL "Debug" )
 FIND_LIBRARY( OSG_LIB "${OSG_LIB_NAME}${CMAKE_DEBUG_POSTFIX}" PATHS ${OSG_LIB_DIR} )
 FIND_LIBRARY( OSGDB_LIB "${OSGDB_LIB_NAME}${CMAKE_DEBUG_POSTFIX}" PATHS $ENV{OSG_LIB_DIR} )
 FIND_LIBRARY( OSGUTIL_LIB "${OSGUTIL_LIB_NAME}${CMAKE_DEBUG_POSTFIX}" PATHS $ENV{OSG_LIB_DIR} )
 FIND_LIBRARY( OSGFX_LIB "${OSGFX_LIB_NAME}${CMAKE_DEBUG_POSTFIX}" PATHS $ENV{OSG_LIB_DIR} ) 
ELSE( CMAKE_BUILD_TYPE STREQUAL "Release" )
 FIND_LIBRARY( OSG_LIB "${OSG_LIB_NAME}" PATHS $ENV{OSG_LIB_DIR} )
 FIND_LIBRARY( OSGDB_LIB "${OSGDB_LIB_NAME}" PATHS $ENV{OSG_LIB_DIR} )
 FIND_LIBRARY( OSGUTIL_LIB "${OSGDB_LIB_NAME}" PATHS $ENV{OSG_LIB_DIR} )
 FIND_LIBRARY( OSGFX_LIB "${OSGDB_LIB_NAME}" PATHS $ENV{OSG_LIB_DIR} ) 
ENDIF( CMAKE_BUILD_TYPE STREQUAL "Debug" )


