(function(){
var e=false,g=null,h=true,k={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",
google_color_text:"color_text",google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",
google_gl:"gl",google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_targeting:"targeting",google_ui_features:"ui",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type",google_page_url:"url"},aa={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_override:"google_ad_override",google_ad_slot:"slotname",
google_analytics_uacct:"ga_wpids",google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",
google_rt:"rt",google_skip:"skip"};function l(){}l.prototype.w=function(){};l.prototype.H=function(){};l.prototype.R=function(){};var n=g;function o(a){n&&n.w(a)}function p(a){n&&n.H(a)}function q(a){n&&n.R(a)}function r(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==g)this._domain_=document.domain}r.prototype.toString=function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"};
function t(){this.G=this.cb();this.W=e;if(!this.G){this.W=this.Da();this.W||p("Browser does not allow cookies")}}t.prototype.ea="__gads=";t.prototype.T="GoogleAdServingTest=";t.prototype.Wa=function(){return this.G};t.prototype.Pa=function(){return this.W};t.prototype.setCookieInfo=function(a){this.z=a._cookies_[0];if(this.z!=g){this.G=this.z._value_;this.mb()}};t.prototype.ia=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c};
t.prototype.La=function(){var a=15552000000,b=this.ia(a),c="ID=12345:T="+a,d="/",f=document.domain;return new r(c,b.valueOf(),d,f)};t.BASE_COOKIE_URL="http://partner.googleadservices.com/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo";
t.prototype.Ga=function(a){if(this.G!=g||!this.W){o("Skipping fetch cookie call");return}var b="script",c=document.domain,d=t.BASE_COOKIE_URL+"&client="+u(a)+"&domain="+u(c);o("Issuing a fetch cookie call with <a href='"+d+"'>"+d+"</a>");document.write("<"+b+' src="'+d+'"></'+b+">")};t.prototype.Da=function(){document.cookie=this.T+"Good";var a=this.qa(this.T),b=a=="Good";if(b){var c=this.ia(-1);document.cookie=this.T+"; expires="+c.toGMTString()}return b};
t.prototype.cb=function(){var a=this.qa(this.ea);a!=g?o("Read first party cookie: "+a):p("No first party cookie found");return a};t.prototype.qa=function(a){var b=document.cookie,c=b.indexOf(a),d=g;if(c!=-1){var f=c+a.length,i=b.indexOf(";",f);if(i==-1)i=b.length;d=b.substring(f,i)}return d};
t.prototype.mb=function(){if(this.z==g)p("Skipping cookie creation: no cookie info");else if(this.G==g)q("Skipping cookie creation: no cookie value");else{var a=new Date;a.setTime(1000*this.z._expires_);var b=this.z._domain_,c=this.ea+this.G+"; expires="+a.toGMTString()+"; path="+this.z._path_+"; domain=."+b;document.cookie=c;o("Written cookie: "+c)}};
function ba(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){var b=3,c=1;while(c)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=g}return b.toString()}else if(v()){var c=g;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){var b=0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
b=6;c.AllowScriptAccess="always"}catch(d){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(d){}}if(c!=g){var b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"};var w=document,x=navigator,y=window;
function ca(){var a=w.cookie,b=Math.round((new Date).getTime()/1000),c=y.google_analytics_domain_name,d=typeof c=="undefined"?z("auto"):z(c),f=a.indexOf("__utma="+d+".")>-1,i=a.indexOf("__utmb="+d)>-1,j=a.indexOf("__utmc="+d)>-1,m,s={};if(f){m=a.split("__utma="+d+".")[1].split(";")[0].split(".");s.sid=i&&j?m[3]+"":y&&y.gaGlobal&&y.gaGlobal.sid?y.gaGlobal.sid:b+"";s.vid=m[0]+"."+m[1];s.from_cookie=h}else{s.sid=y&&y.gaGlobal&&y.gaGlobal.sid?y.gaGlobal.sid:b+"";s.vid=y&&y.gaGlobal&&y.gaGlobal.vid?y.gaGlobal.vid:
(A()^da()&2147483647)+"."+b;s.from_cookie=e}s.dh=d;s.hid=y&&y.gaGlobal&&y.gaGlobal.hid?y.gaGlobal.hid:A();y.gaGlobal=s;return s}function A(){return Math.round(Math.random()*2147483647)}
function da(){var a=w.cookie?w.cookie:"",b=y.history.length,c,d,f=[x.appName,x.version,x.language?x.language:x.browserLanguage,x.platform,x.userAgent,x.javaEnabled()?1:0].join("");if(y.screen)f+=y.screen.width+"x"+y.screen.height+y.screen.colorDepth;else if(y.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();f+=d.screen.width+"x"+d.screen.height}f+=a;f+=w.referrer?w.referrer:"";c=f.length;while(b>0)f+=b--^c++;return fa(f)}
function fa(a){var b=1,c=0,d,f;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){f=a.charCodeAt(d);b=(b<<6&268435455)+f+(f<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function z(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=w.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return fa(a.toLowerCase())};window.googleSkipProperty=function(a){return typeof a=="function"};if(!Array.prototype.push)Array.prototype.push=function(){for(var a=0;a<arguments.length;a++)this[this.length]=arguments[a];return this.length};if(window._GA_googleAdData==g)window._GA_googleAdData=new B;if(window._GA_googleAdEngine==g)window._GA_googleAdEngine=g;
window.GA_googleAddSlot=function(a,b){if(a==g||a.length==0){q("publisher id cannot be null or empty");return g}else if(b==g||b.length==0){q("slot name cannot be null or empty for publisher "+a);return g}var c=new C(a,b);return window._GA_googleAdData.fa(c)};window._GA_googleInitializeAdEngine=function(a){if(!window._GA_googleAdEngine){window._GA_googleAdEngine=E.newInstance(a);window._GA_googleAdEngine.initialize()}};
window.GA_googleFetchAds=function(){window._GA_googleAdData.rb=h;window._GA_googleInitializeAdEngine(g);var a=window._GA_googleAdEngine.t;if(a==E.SYNC||a==E.SYNC_SRA){o("Synchronous implementation: Skipping slotdata request");window._GA_googleAdEngine.l()}else window._GA_googleAdData.Ha()};window.GA_googleUseIframeRendering=function(){window._GA_googleInitializeAdEngine(E.IFRAME);window._GA_googleCookieHelper.Ga(window.GS_googleGetIdsForAdSenseService())};
window.GA_googleUseSyncSRARendering=function(){var a=G.getParameter("google_ad_impl");a==g&&G.setParameter("google_ad_impl",E.SYNC_SRA)};
window.GA_googleFillSlot=function(a){if(window._GA_googleAdEngine==g){q('GA_googleFetchAds() must be called prior to GA_googleFillSlot("'+a+'") ');return}if(window._GA_googleAdEngine.t==E.IFRAME){q("Use GA_googleFillSlotWithSize(client, slotname, width, height) for iframe rendering instead of GA_googleFillSlot()");return}if(window._GA_googleAdEngine.ca())if(window._GA_googleAdEngine.ba){var b=window._GA_googleAdData.s(a);if(b==g){q('Skipping undefined Ad Slot("'+a+'")');return}else if(!b._enabled_){o('Skipping disabled Ad Slot("'+
a+'")');return}}else{q("Unable to retrieve AdSlot information");return}else if(window._GA_googleAdEngine.A(a)!=g&&!window._GA_googleAdEngine.r){p("FillSlot() called again for "+a);return}window._GA_googleAdEngine.n(a)};
window.GA_googleFillSlotWithSize=function(a,b,c,d){if(window._GA_googleAdEngine==g){q("GA_googleUseIframeRendering() must be called prior to  GA_googleFillSlotWithSize() ");return}if(window._GA_googleAdEngine.t!=E.IFRAME){q("GA_googleFillSlotWithSize() is only supported for iframe rendering. Enable iframe rendering with GA_googleUseIframeRendering() or use GA_googleFillSlot()");return}var f=new C(a,b);window._GA_googleAdData.fa(f);var i=new ga(c,d,e,h);window._GA_googleAdData.xa(b,i);window._GA_googleAdEngine.n(b)};
window.GA_googleAddAttr=function(a,b){window._GA_googleAdData.ya(a,b)};window.GA_googleAddAdSensePageAttr=function(a,b){window._GA_googleAdData.va(a,b)};window.GA_googleAddAdSenseSlotAttr=function(a,b,c){window._GA_googleAdData.wa(a,b,c)};window.GA_googleResetAll=function(){window._GA_googleAdData=new B;window._GA_googleAdEngine=g};window.google_noFetch=e;window.GA_googleNoFetch=function(){window.google_noFetch=h};window.GA_googleDelayFetch=function(){window.google_delayFetch=h};
function ga(a,b,c,d){this._width_=a;this._height_=b;this._expandable_=c;this._enabled_=d}ga.prototype.toString=function(){return"[GA_GoogleAdAttr: width="+this._width_+", height="+this._height_+", expandable="+this._expandable_+", enabled="+this._enabled_+"]"};
function ha(a){var b={},c=a.split("?"),d=c[c.length-1].split("&");for(var f=0;f<d.length;f++){var i=d[f].split("=");if(i[0])try{b[i[0].toLowerCase()]=i.length>1?window.decodeURIComponent?decodeURIComponent(i[1].replace(ia," ")):unescape(i[1]):""}catch(j){}}return b}function H(a){var b=a||document.URL;this.bb=ha(b)}H.prototype.getParameter=function(a){return a==g?g:this.bb[a]};H.prototype.setParameter=function(a,b){this.bb[a]=b};
H.prototype.debug=function(){o("publisher URL="+document.URL);o("user agent="+navigator.userAgent);o("appVersion="+navigator.appVersion)};if(typeof G=="undefined")var G=new H;var ja=/function (^\w+)/;function ka(a){var b=ja.exec(String(a));if(b)return b[1];return""}
function la(a){try{if(!a)return"";var b=ka(a),c="";if(b!=g&&b.length>0&&b!="anonymous"){c="- "+b+"(";for(var d=0;d<a.arguments.length;d++){if(d>0)c+=", ";var f=String(a.arguments[d]);if(f.length>80)f=f.substr(0,80)+"...";c+=f}c+=")<br>"}c+=la(a.caller);return c}catch(i){return"[Cannot get stack trace]: "+i+"\n"}}function u(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}
function J(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;")}function K(){this.f=g;this.P=e;this.V=g;this.isDebug=G.getParameter("google_debug")!=g;this.isDebug&&this.J()}K.prototype.Sa=function(){var a=(new Date).valueOf();if(this.V==g)this.V=a;return a-this.V};K.prototype.oa=0;
K.prototype.J=function(){if(this.f!=g)return;else if(this.P)return;else{this.f=window.open("","GoogleDebug","width=1100, height=600, status=no, resizable=yes, scrollbars=yes");if(!this.f){this.P=h;return}var a=this.f.document,b="";b+="<html>";b+="<head><title>Google Ad Manager Debug Output</title><style>";b+="h2 {font-size: 1em;margin: 0 0 0.5em 0;color: #353C43}";b+="th {background: #e5e5e5;font-weight: normal;color: #444444;";b+="text-align: left;}";b+="td {border-bottom: 1px solid #dddddd}";b+=
"tbody tr:hover {background: #ffffcc}";b+=".dn {display: none;} .lightText {color: #a0a0a0;}";b+="</style>";b+="</head>";b+="<body><h2>Google Ad Manager Debug Output</h2><br/>";b+='Page URL: <span id="pageUrl"></span><br/><br/>';b+='<form action="" method="post">';b+='<table id="google_slot_table" width="100%" class="dn" ';b+='cellspacing="0">';b+="<thead><tr><th>&nbsp;";b+='<span id="numSlots">0</span> slots on page</th>';b+="<th>&nbsp;</th></tr><tr>";b+="<th>&nbsp;&nbsp;Ad Slot Name</th>";b+="<th>Delivery Analysis ";
b+='<span class="lightText">(login required)</span></th>';b+="</tr></thead>";b+="<tbody>";b+='<tr class="dn"><td></td><td></td></tr>';b+="</tbody></table><br/>";b+='<table id="google_msg_table" width="100%" cellspacing="0">';b+="<thead><tr><th>Offset (msec)</th><th>Type</th>";b+="<th>Message</th></tr></thead>";b+='<tbody id="google_msg_body">';b+='<tr class="dn"><td></td><td></td><td></td></tr>';b+="</tbody></table></form></body></html>";a.write(b);a.getElementById("pageUrl").innerHTML=J(document.URL);
a.close();var c=a.getElementById("google_slot_table");this.oa=c.rows.length}};K.prototype.w=function(a){this.S("Information",a)};K.prototype.H=function(a){this.S("Warning",a)};K.prototype.R=function(a){this.S("Error",a)};K.colorTable={Information:"black",Warning:"orange",Error:"red"};K.prototype.X=function(a,b){return"<font color='"+K.colorTable[a]+"'>"+b+"</font>"};
K.prototype.nb=function(a,b){var c=this.f;if(!c)return;var d=this.f.document.getElementById("google_slot_table");if(d!=g){if(d.className=="dn")d.className="";var f=d.insertRow(-1),i=f.insertCell(0);i.innerHTML=a;i=f.insertCell(1);var j="";j+='<a href="'+b+'" target="_blank">';j+="Details</a>";i.innerHTML=j;this.f.document.getElementById("numSlots").innerHTML=d.rows.length-this.oa}else alert("failed to add to console: "+a)};
K.prototype.S=function(a,b){var c=this.f;if(!c)return;var d=this.f.document.getElementById("google_msg_table");if(d!=g){var f=d.insertRow(-1),i=f.insertCell(0);i.innerHTML=this.X(a,""+this.Sa());var j=f.insertCell(1);j.innerHTML=this.X(a,a+"&nbsp;&nbsp;");var m=f.insertCell(2),s=la(this.S.caller);if(s.length>0){b+="<br>Triggered by: <br>";b+=s}m.innerHTML=this.X(a,b)}else alert("fails to add to console: "+a+", "+b)};if(n==g)n=new K;o("google_ads.js is being loaded at "+(new Date).toLocaleString());
G.debug();function L(){this.f=g;this.P=e;this.V=(new Date).valueOf()}
L.prototype.J=function(a){if(this.f!=g)return;else if(this.P)return;else{this.f=window.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes");if(!this.f){this.P=h;return}var b=this.f.document,c=[];c.push('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');c.push("<p>Google Ad Capture Window</p>");
for(var d in a){if(window.googleSkipProperty(a[d]))continue;c.push(this.lb(d,a[d]))}c.push("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");c.push("<script>displayTime('blocked', pageStartTime);<\/script>");c.push("<p>Total Page Load Time (ms): <label id='total'></label>");c.push("</body>\n</html>");var f=c.join("\n"),i=G.getParameter("google_capture_norender")!=g;i?b.write(J(f)):b.write(f);b.close()}};
L.prototype.lb=function(a,b){var c="<script>slotStartTime = (new Date()).valueOf();<\/script>",d="<p>Slot "+a+"</p>",f;f=b==g||b._html_==g?"No ad":b._html_;var i="<p>Slot Time (ms): <label id='"+a+"'></label>",j='<script>displayTime("'+a+'", slotStartTime);<\/script>';return c+d+"\n"+f+"\n"+i+j};if(typeof ma=="undefined")var ma=new L;if(window._GA_googleCookieHelper==g)window._GA_googleCookieHelper=new t;function M(){this.g={}}M.ParamComponents={PAGE_LEVEL:0,SLOT_LEVEL:1};
M.prototype.U=function(a,b,c){if(a)b||(b="");else{q("cannot add attribute whose key is null or blank");return}if(!(a in k)){p("Skipping unknown adsense attribute: "+a+" in the request");return}c=typeof c=="undefined"||c;if(c||!this.g[a])this.g[a]=b;o("added adsense parameter="+a+" with value="+b)};M.prototype.$a=function(a){for(var b in a.g){if(window.googleSkipProperty(a.g[b]))continue;this.g[b]||(this.g[b]=a.g[b])}};M.prototype.getAttribute=function(a){return this.g[a]};M.prototype.ja=function(){return this.g};
M.prototype.h=function(){var a=[];for(var b in this.g){if(window.googleSkipProperty(this.g[b]))continue;if(b=="google_gl"&&this.g.google_country!=g)continue;var c=k[b]||aa[b]||g,d=this.g[b];c&&d&&a.push(c+"="+u(d))}return a.join("&")};
M.generateBatchedAfcParams=function(a,b,c,d){var f=M.generatePageAndSlotAfcParamComponents(a,b,c,d),i=[];f[M.ParamComponents.PAGE_LEVEL]&&f[M.ParamComponents.PAGE_LEVEL].length>0&&i.push(f[M.ParamComponents.PAGE_LEVEL].join("&"));f[M.ParamComponents.SLOT_LEVEL]&&f[M.ParamComponents.SLOT_LEVEL].length>0&&i.push("sps="+f[M.ParamComponents.SLOT_LEVEL].join("|"));return i.join("&")};
M.generatePageAndSlotAfcParamComponents=function(a,b,c,d){var f=[],i=[],j=b.ja();for(var m in d){if(window.googleSkipProperty(m))continue;var s=d[m];if(!s)continue;var I="";if(j[m]!=g)I=u(j[m]);var D=[],F=-1,S=-1;for(var T in a){if(window.googleSkipProperty(a[T]))continue;else++F;if(c[T]==g){D.push("");continue}var ea=c[T].ja();if(ea[m]!=g){D.push(u(u(ea[m])));S=F}else D.push("")}if(S>=0){var na=u(I),U=[];U.push(na);for(var V=0;V<=S;++V)U.push(D[V]);i.push(s+","+U.join(","))}else I&&f.push(s+"="+
I)}var W=[];W.push(f);W.push(i);return W};function C(a,b){this.pa=a;this.q=b;this.da=0;this.O=0;this.ha=e;this.eb=e;this.Ia=g;this.ga=g;this.db=g;this.ra=g}C.prototype.sa=function(){this.ha=h;this.Ia=(new Date).valueOf()};C.prototype.gb=function(){this.ga=(new Date).valueOf()};C.prototype.M=function(){if(this.ha&&this.ga!=g)return this.ga-this.Ia;return 0};C.prototype.ib=function(){this.eb=h;this.db=(new Date).valueOf()};C.prototype.hb=function(){this.ra=(new Date).valueOf()};
C.prototype.N=function(){if(this.eb&&this.ra!=g)return this.ra-this.db;return 0};C.prototype.toString=function(){return"[GA_GoogleAdSlot: pubid="+this.pa+", name="+this.q+", loaded="+this.O+", tries="+this.da+"]"};C.prototype.kb=function(){return"Slot: publisher id="+this.pa+", name="+this.q};function B(){this.c={};this.o=[];this.D={};this.ab=new M;this.Q={};this.rb=e;this.i=g}
B.prototype.fa=function(a){var b=this.c[a.q];b?q("Slot "+a.q+" has already been defined"):o(a.kb()+" has been added");this.c[a.q]=a;return a};B.prototype.ka=function(){var a=0;for(var b in this.c){if(window.googleSkipProperty(this.c[b]))continue;var c=this.s(b),d=this.c[b];c!=g&&c._enabled_&&!d.ha&&a++}return a};B.prototype.Ra=function(){var a=0;for(var b in this.c){if(window.googleSkipProperty(this.c[b]))continue;var c=this.s(b);c!=g&&c._enabled_&&a++}return a};
B.prototype.na=function(){for(var a in this.c){if(window.googleSkipProperty(this.c[a]))continue;var b=this.c[a];b.sa()}};B.prototype.ma=function(a){var b=this.c[a];b.sa()};B.prototype.la=function(a){var b=this.c[a];b.gb()};B.prototype.Za=function(a){var b=this.c[a];b.ib()};B.prototype.u=function(a){var b=this.c[a];b.hb()};B.prototype.M=function(){var a=0;for(var b in this.c){if(window.googleSkipProperty(this.c[b]))continue;a+=this.c[b].M()}return a};
B.prototype.N=function(){var a=0;for(var b in this.c){if(window.googleSkipProperty(this.c[b]))continue;a+=this.c[b].N()}return a};B.prototype.toString=function(){var a="[AdData:",b=[];for(var c in this.c){if(window.googleSkipProperty(this.c[c]))continue;b.push(this.c[c].toString())}for(var d in this.D){if(window.googleSkipProperty(this.D[d]))continue;b.push("["+d+","+this.D[d]+"]")}a+=b.join();a+="]";return a};B.prototype.p=function(a){return this.c[a]};
B.prototype.ya=function(a,b){if(a==g||a.length==0){q("cannot add attribute whose key is null or blank");return}else if(b==g||b.length==0)b="";var c=this.D[a];this.D[a]=c==g?b:c+","+b;o("added attribute with key="+a+" and value="+b)};B.prototype.va=function(a,b){this.ab.U(a,b)};B.prototype.Y=function(){return this.ab};
B.prototype.wa=function(a,b,c){if(a==g||a.length==0){q("cannot add attribute to a null or blank adslot");return}if(window._GA_googleAdEngine==g||window._GA_googleAdEngine.t!=E.IFRAME){var d=this.p(a);if(d==g){p("Trying to add adsense attribute to a non-existent or disabled slot: "+a);return}}var f=this.Q[a];if(f==g)this.Q[a]=new M;this.Q[a].U(b,c)};B.prototype.Oa=function(a){return this.Q[a]};B.BASE_SLOTATTR_URL="http://partner.googleadservices.com/gampad/slotdata.js?callback=_GA_googleAdData.setAdSlotAttributes";
B.prototype.Ha=function(){if(this.i!=g){window._GA_googleAdEngine.l();return}o(window._GA_googleAdData.toString());var a=[];for(var b in this.c){if(window.googleSkipProperty(this.c[b]))continue;a.push(b)}var c=window.GS_googleGetIdsForAdSenseService(),d=B.BASE_SLOTATTR_URL+"&client="+escape(c)+"&page_slots="+escape(a.join());o("Issuing fetch ad attr call with <a href='"+d+"'>"+d+"</a>");document.write("<script src = '"+d+"'><\/script>")};
B.prototype.setAdSlotAttributes=function(a){this.i=a;o("Attributes received for slots "+this.ua());window._GA_googleAdEngine.ba=h;window._GA_googleAdEngine.l()};B.prototype.xa=function(a,b){if(this.i==g)this.i={};this.i[a]=b;o("Attributes added for slot "+a);window._GA_googleAdEngine.ba=h};
B.prototype.ua=function(){var a=[];for(var b in this.i){if(window.googleSkipProperty(this.i[b]))continue;var c=this.i[b];if(this.c[b]==g)continue;a.push("["+b+": width="+c._width_+", height="+c._height_+", expandable="+c._expandable_+", enabled="+c._enabled_+"]")}return a.join()};B.prototype.s=function(a){return this.i!=g?this.i[a]:g};function N(a,b){this.ub=a;this.qb=b}N.HTML_TYPE="html";N.JS_TYPE="js";function O(a,b){this.AdSlotContent=N;this.AdSlotConent(O.HTML_TYPE,a);this._html_=b}
O.prototype.toString=function(){return"[GA_HTMLAdSlotContent expandable="+this.qb+", html="+this._html_+"]"};O.prototype=new N(O.HTML_TYPE,e);P.BASE_URL="http://partner.googleadservices.com/gampad/ads?";P.MAX_URL_LENGTH=2000;function P(a){this.e=g;this.i={};this.b=g;this.C=n;this.r=a;this.v=e;this.F=e;this.j=e;this.t=E.SYNC;this.tb=k}
P.prototype.initialize=function(){this.v=G.getParameter("google_nofetch")!=g||window.google_noFetch;this.F=G.getParameter("google_norender")!=g;this.j=G.getParameter("google_capture")!=g||G.getParameter("google_capture_norender")!=g;if(this.j)this.F=h;if(window.attachEvent)window.attachEvent("onload",function(){return window._GA_googleAdEngine.generateSummary()});else window.addEventListener&&window.addEventListener("load",function(){return window._GA_googleAdEngine.generateSummary()},e);this.v&&
p("Fetching Ads from Google has been suppressed");this.F&&p("Rendering Ads from Google has been suppressed");this.j&&p("Ads from Google are sent to Capture window")};P.prototype.generateSummary=function(){o("Time the page is blocked fetching ads from Google "+window._GA_googleAdData.M()+" ms");o("Time the page is blocked rendering ads from Google "+window._GA_googleAdData.N()+" ms");o("Page loaded");this.j&&ma.J(this.e)};
P.prototype.m=function(){var a=G.getParameter("google_ad_url");if(a==g||a.length==0)this.b=P.BASE_URL;else{if(a.charAt(a.length-1)!="?")a+="?";o("Using a new ad url "+a);this.b=a}};P.prototype.A=function(a){return this.e!=g?this.e[a]:g};P.prototype.Va=function(){if(this.e==g)return"No content";else{var a=[];for(var b in this.e){if(window.googleSkipProperty(this.e[b]))continue;if(window._GA_googleAdData.p(b)==g)continue;a.push(b)}return a.join()}};
P.getIEVersionNumber=function(){var a=navigator.userAgent,b=a.indexOf("MSIE ");return b==-1?0:parseFloat(a.substring(b+5,a.indexOf(";",b)))};var ia=/\+/g;P.prototype.Xa=function(a){a=a.toLowerCase();if(a.substring(0,3)!="ca-")a="ca-"+a;return a};P.prototype.d=function(a,b){b!=g&&this.a(a,u(b))};P.prototype.a=function(a,b){if(b!=g)this.b+=this.b.charAt(this.b.length-1)!="?"?"&"+a+"="+b:a+"="+b};
P.prototype.Na=function(a){var b=window._GA_googleAdData.c,c=[],d=[],f=[];for(var i in b){if(window.googleSkipProperty(b[i]))continue;if(this.ca()){var j=window._GA_googleAdData.s(i);if(j==g||!j._enabled_)continue}var m=b[i];f.push(m.q);if(a!=g&&a!=m.q)continue;c.push(m.q);d.push(this.Xa(m.pa))}this.d("client",d[0]);this.d("slotname",c.join());if(this.r)f.length>0&&this.d("page_slots",f.join());else window._GA_googleAdData.o.length>0&&this.d("page_slots",window._GA_googleAdData.o.join())};
P.prototype.Ua=function(a,b){if(b!=g){var c=a.lastIndexOf("?"),d=a.indexOf("google_preview=",c),f=a.indexOf("&",d);if(f==-1){f=a.length-1;d-=1}return a.substring(0,d)+a.substring(f+1,a.length)}return a};P.prototype.Ta=function(){var a=window._GA_googleAdData.Y().getAttribute("google_page_url");if(a)return a;return document.URL};
P.prototype.Ja=function(a,b,c){this.d("url",this.Ua(this.Ta(),G.getParameter("google_preview")));this.d("ref",document.referrer);this.d("lmt",Date.parse(document.lastModified)/1000);this.a("dt",a.getTime());if(document.body){var d=document.body.scrollHeight,f=document.body.clientHeight;f&&d&&this.d("cc",Math.round(f*100/d))}var i=G.getParameter("deb");i!=g&&this.d("deb",i);var j=G.getParameter("haonly");j!=g&&this.d("haonly",j);if(navigator.userAgent.indexOf("MSIE ")>0){var m=window._GA_googleAdData.Y();
m.U("google_encoding",document.charset,e)}var s=window._GA_googleAdData.c,I=window._GA_googleAdData.Q,D=window._GA_googleAdData.Oa(b),m=window._GA_googleAdData.Y(),F="";if(c)F=M.generateBatchedAfcParams(s,m,I,this.tb);else{if(D==g)D=m;else D.$a(m);F=D.h()}if(F)this.b+="&"+F};
P.prototype.Ma=function(){var a=window._GA_googleAdData.D,b=[];for(var c in a){if(window.googleSkipProperty(a[c]))continue;b.push(u(c)+"="+u(a[c]))}this.d("cust_params",b.join("&"));this.d("cookie",window._GA_googleCookieHelper.Wa());window._GA_googleCookieHelper.Pa()&&this.d("cookie_enabled",1)};P.prototype.Ka=function(){ca();var a=window;this.a("ga_vid",a.gaGlobal.vid);this.a("ga_sid",a.gaGlobal.sid);this.a("ga_hid",a.gaGlobal.hid);this.a("ga_fc",a.gaGlobal.from_cookie);this.d("ga_wpids",a.google_analytics_uacct)};
P.prototype.Ya=function(a,b){var c=a.screen,d=navigator.javaEnabled(),f=-b.getTimezoneOffset();if(c){this.a("u_h",c.height);this.a("u_w",c.width);this.a("u_ah",c.availHeight);this.a("u_aw",c.availWidth);this.a("u_cd",c.colorDepth)}this.a("u_tz",f);this.a("u_his",window.history.length);this.a("u_java",d);navigator.plugins&&this.a("u_nplug",navigator.plugins.length);navigator.mimeTypes&&this.a("u_nmime",navigator.mimeTypes.length);this.a("flash",ba())};
P.prototype.h=function(a){this.m();var b=new Date;this.Na(a);this.Ma();G.getParameter("google_preview")!=g&&this.a("gct",G.getParameter("google_preview"));this.Ka();this.Ja(b,a,this.r);this.Ya(window,b);this.b.length>P.MAX_URL_LENGTH&&q("Truncated URL with length "+this.b.length+" bytes to "+P.MAX_URL_LENGTH+" bytes: "+this.b);this.b=this.b.substring(0,P.MAX_URL_LENGTH);this.b=this.b.replace(/%\w?$/,"");return this.b};P.IFRAME_PREFIX="google_ads_iframe_";P.IFRAME_PREFIX_LEN=P.IFRAME_PREFIX.length;
P.jb=h;P.ba=e;P.prototype.ca=function(){return P.jb};P.prototype.$=function(a){return P.IFRAME_PREFIX+a};P.prototype.B=function(a){var b=a.getAttribute("id"),c=b.substr(P.IFRAME_PREFIX_LEN,b.length-P.IFRAME_PREFIX_LEN);return c};
P.prototype.K=function(a,b,c,d,f){var i=this.Z(a),j=this.$(a),m="<div id="+i+">",s="scrolling="+(this.j?'"auto"':'"no"');m+="<iframe id="+j+" name="+j+' width="'+d+'" height="'+f+'" vspace="0" hspace="0" allowtransparency="true" '+s+' marginwidth="0" marginheight="0" frameborder="0" style="border:0px;" src="'+J(b)+'"';if(c!=g)m+=' onload="'+c+'"';m+="></iframe></div>";c!=g?o("Generated iframe for slot "+a+" width:"+d+" height:"+f+" with <a href='"+b+"'>"+b+"</a> and content="+J(m)):o("Generated iframe for slot "+
a+" width:"+d+" height:"+f+" with <a href='"+b+"'>"+b+"</a>");document.write(m)};
P.prototype.createDOMIframe=function(a,b){var c=this.A(b),d=c._width_,f=c._height_,i=c._html_,j=document.createElement("iframe");j.id=this.$(b);j.name=this.$(b);j.width=d;j.height=f;j.vspace=0;j.hspace=0;j.allowTransparency="true";j.scrolling="no";j.marginWidth=0;j.marginHeight=0;j.frameBorder=0;j.style.border=0;var m=document.getElementById(a);m.appendChild(j);if(this.j){j.contentWindow.document.write(J(i));j.scrolling="auto"}else j.contentWindow.document.write(i);j.contentWindow.document.close();
window._GA_googleAdData.u(b)};P.pb=function(){var a=[],b=document.getElementsByTagName("base");if(b)for(var c=0,d=b.length;c<d;++c){var f=b[c],i=f.getAttribute("target");if(i){a.push({baseElement:f,originalTagValue:i});f.removeAttribute("target")}}return a};P.ob=function(a){if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}};
P.sb=function(a){var b="http://pagead2.googlesyndication.com/pagead/inject_object_div.js";if(parseInt(P.getIEVersionNumber(),10)>6)return e;if(a.indexOf(b)<0)return e;return h};P.prototype.za=function(a,b){if(this.j)b=J(b);var c=P.pb();window.frames[a.name].contents=b;a.src=P.sb(b)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';P.ob(c)};
P.prototype.Aa=function(a,b){var c=this.B(a),d=a.contentWindow?a.contentWindow.document:a.contentDocument;if(d==g)if(document.implementation&&document.implementation.createDocument)d=document.implementation.createDocument("",c,g);else if(typeof ActiveXObject!="undefined")d=new ActiveXObject("Msxml.DOMDocument");else{this.C.R("Cannot create document in iframe for slot "+c+" with "+J(b));return}d.open("text/html","replace");this.j?d.write(J(b)):d.write(b);d.close()};
P.prototype.loadiframe=function(a){var b=this.B(a),c=window._GA_googleAdData.p(b);if(c.O)return;c.O=h;var d=this.A(b),f=a.parentNode;if(d==g||d._html_==g){f.removeChild(a);this.C.H("Removed iframe for slot due to lack of content: "+b);window._GA_googleAdData.u(b);return}else if(d._expandable_){f.innerHTML=d._html_;window._GA_googleAdData.u(b);return}d._is_3pas_?this.za(a,d._html_):this.Aa(a,d._html_);window._GA_googleAdData.u(b);this.C.w("Filling iframe for slot "+b+" with "+J(d._html_))};
P.DIV_PREFIX="google_ads_div_";P.DIV_PREFIX_LEN=P.DIV_PREFIX.length;P.prototype.Z=function(a){return P.DIV_PREFIX+a};P.prototype.Ca=function(a){var b=this.Z(a),c="<div id="+b+">",d=this.A(a);if(d==g){this.C.H("Suppressing div for slot due to lack of content: "+a);return}c+=d._html_;c+="\n</div>\n";o("Generated div for slot "+a+" with "+J(c));document.write(c);window._GA_googleAdData.u(a);return b};
P.prototype.Ba=function(a){var b=this.Z(a),c="<div id="+b+">";c+="\n</div>\n";o("Generated div for iframe for slot "+a);document.write(c);return b};P.prototype.I=function(){if(!this.ca())return h;if(window._GA_googleAdData.ka()>0)return h;else if(window._GA_googleAdData.Ra()==0){p("No slots defined on page");return e}};
P.prototype.setAdContentsBySlot=function(a){if(this.e==g){this.e=a;for(var b in a){if(window.googleSkipProperty(a[b]))continue;window._GA_googleAdData.la(b)}}else for(var b in a){if(window.googleSkipProperty(a[b]))continue;this.e[b]=a[b];window._GA_googleAdData.la(b)}o("Confirmed response for slots "+this.Va());var c=e;for(var b in a){if(window.googleSkipProperty(a[b]))continue;var d=a[b];if(c){d._cookies_=[window._GA_googleCookieHelper.La()];c=e}d!=g&&d._cookies_!=g&&window._GA_googleCookieHelper.setCookieInfo(d)}};
function Q(a){this.AdEngine=P;this.AdEngine(a);this.AdEngine.jb=e;this.k=(new Date).getTime();o("Generated a correlator="+this.k);this.t=a?E.SYNC_SRA:E.SYNC}Q.prototype=new P(e);
Q.prototype.m=function(){var a=G.getParameter("google_ad_url");if(a==g)this.b=P.BASE_URL;this.d("correlator",this.k);this.a("output","json_html");this.a("callback","_GA_googleAdEngine.setAdContentsBySlotForSync");this.r?this.a("impl","ss"):this.a("impl","s");var b=0,c=h;for(var d in this.e){if(window.googleSkipProperty(this.e[d]))continue;var f=this.e[d];if(f._is_afc_==undefined){c=e;break}else b=2*b+(f._is_afc_?1:0)}c&&this.a("prev_afc",b)};
Q.prototype.Qa=function(a){var b=P.BASE_URL,c="debugDelivery?"+a.substring(b.length)+"&base_url="+encodeURIComponent(b);return"http://www.google.com/admanager/"+c};
Q.prototype.Fa=function(a){var b=window._GA_googleAdData.c,c=b[a];if(c==g)q("Skipping undefined AdSlot "+a);else if(this.v)o("Skip Issuing fetch ads call for "+a);else{this.h(c.q);window._GA_googleAdData.ma(a);o("Issuing fetch ads call with <a href='"+this.b+"'>"+this.b+"</a>");n.nb(a,this.Qa(this.b));document.write("<script src = '"+this.b+"'><\/script>")}};
Q.prototype.setAdContentsBySlotForSync=function(a){this.setAdContentsBySlot(a);if(this.r)if(window._GA_googleAdData.o.length==1){var b=window._GA_googleAdData.o[0];o("Filling contents for first slot: "+b);this.aa(b);return}else q("Ad request should be sent from the first  fillSlot call for SRA");for(var c in a){if(window.googleSkipProperty(a[c]))continue;this.aa(c)}};Q.prototype.l=function(){if(!this.I())return};
Q.prototype.Ea=function(){this.h(g);o("Issuing SRA fetch ads call with <a href='"+this.b+"'>"+this.b+"</a>");document.write("<script src = '"+this.b+"'><\/script>");window._GA_googleAdData.na()};Q.prototype.n=function(a){window._GA_googleAdData.o.push(a);if(this.r)if(window._GA_googleAdData.o.length==1)this.Ea();else{o("Now really fill contents for adslot: "+a);this.aa(a)}else this.Fa(a)};
Q.prototype.aa=function(a){var b=window._GA_googleAdData.p(a);if(b==g){q("This slot has not been defined: "+a);return}var c=this.A(a);window._GA_googleAdData.Za(a);if(c==g||c._empty_){window._GA_googleAdData.u(a);p("Suppressing slot "+a+" due to lack of content")}else if(this.F&&!this.j)window._GA_googleAdData.u(a);else if(c._snippet_&&!c._is_afc_&&!this.j)this.Ca(a);else if(navigator.userAgent.indexOf("MSIE ")>0){var d="_GA_googleAdEngine.syncAdSlotLoaded(this);";this.K(a,"about:blank",d,c._width_,
c._height_)}else{var f=this.Ba(a);document.write("<script>_GA_googleAdEngine.createDOMIframe('"+f+"' ,'"+a+"');<\/script>")}};Q.prototype.syncAdSlotLoaded=function(a){var b=this.B(a),c=window._GA_googleAdData.p(b);c.O||this.C.w("iframe is loaded for slot "+b);this.loadiframe(a)};function R(a){this.AdEngine=P;this.AdEngine(a);this.k=(new Date).getTime();o("Generated a correlator="+this.k);this.t=E.ASYNC}R.prototype=new P(e);
R.prototype.m=function(){var a=G.getParameter("google_ad_url");if(a==g)this.b=P.BASE_URL;this.fb();this.d("correlator",this.k);this.a("output","json_html");this.a("callback","_GA_googleAdEngine.setAdContentsBySlot");this.a("impl","a")};R.MAXTRIES=30;R.DEFAULT_ASYNC_DELAY=500;R.INITIAL_ASYNC_DELAY=20;R.prototype.fb=function(){this.delay=R.DEFAULT_ASYNC_DELAY;var a=G.getParameter("google_async_delay");if(a!=g)this.delay=1000*a};
R.prototype.l=function(){if(!this.I())return;o(window._GA_googleAdData.toString());if(this.v)o("Skip Issuing fetch ads call for all slots");else{o("Set a timer to fetch Ads");window.setTimeout("_GA_googleAdEngine.reallyFetchAds();",this.INITIAL_ASYNC_DELAY)}};
R.prototype.reallyFetchAds=function(){if(window._GA_googleAdData.ka()==0){o("optimized away a fetchAds call");return}var a=document.getElementsByTagName("head")[0];if(this.r){var b=document.createElement("script");b.src=this.h(g);a.appendChild(b);o("Issuing fetch ads call with <a href='"+this.b+"'>"+this.b+"</a>");window._GA_googleAdData.na()}else{var c=window._GA_googleAdData.c;for(var d in c){if(window.googleSkipProperty(c[d]))continue;var b=document.createElement("script");b.src=this.h(d);a.appendChild(b);
o("Issuing fetch ads call for "+d+" with <a href='"+this.b+"'>"+this.b+"</a>");window._GA_googleAdData.ma(d)}}};R.prototype.n=function(a){var b=window._GA_googleAdData.p(a);if(b==g){q("This slot has not been defined: "+a);return}window._GA_googleAdData.o.push(a);var c="_GA_googleAdEngine.asyncAdSlotLoaded(this);",d=window._GA_googleAdData.s(a);this.K(a,"about:blank",c,d._width_,d._height_)};
R.prototype.asyncAdSlotLoaded=function(a){var b=this.B(a),c=window._GA_googleAdData.p(b);c.O||this.C.w("iframe is not loaded for slot "+b);!this.v&&!this.F&&this.ta(a)};R.prototype.ta=function(a){var b=this.B(a),c=window._GA_googleAdData.p(b);if(this.e==g||this.e[b]==g){if(c.da>R.MAXTRIES){q("Giving up on waiting for ads for "+b);return}o("Set a timer to wait for ads for "+b+", tries="+c.da);window.setTimeout(function(){window._GA_googleAdEngine.ta(a)},this.delay);c.da++;return}this.loadiframe(a)};
R.prototype.generateSummary=function(){o("Page loaded")};function X(a){this.AdEngine=P;this.AdEngine(a);this.k=(new Date).getTime();o("Generated a correlator="+this.k);this.t=E.FALLBACK}X.prototype=new P(e);X.prototype.m=function(){var a=G.getParameter("google_ad_url");if(a==g)this.b=P.BASE_URL;this.d("correlator",this.k);this.a("output","html");this.a("impl","fb")};X.prototype.l=function(){if(!this.I())return;o(window._GA_googleAdData.toString())};
X.prototype.L=function(a){var b;if(this.r){this.h(g);b=this.b+"&currentslot="+u(a)}else b=this.h(a);return b};X.prototype.n=function(a){var b=window._GA_googleAdData.s(a);if(b==g){q("This slot has not been defined: "+a);return}window._GA_googleAdData.o.push(a);if(this.v)p("Skip Issuing fetch ads call for "+a);else{var c=this.L(a);this.K(a,c,g,b._width_,b._height_)}};
function Y(a){this.AdEngine=P;this.AdEngine(a);this.k=(new Date).getTime();this.ba=h;this.t=E.IFRAME;o("Generated a correlator="+this.k);this.v&&p("Fetching Ads from Google has been suppressed");if(this.j)p("google_capture is not supported for iframe implementation");else this.F&&p("google_norender is not supported for iframe implementation")}Y.prototype=new P(e);
Y.prototype.m=function(){var a=G.getParameter("google_ad_url");if(a==g)this.b=P.BASE_URL;this.d("correlator",this.k);this.a("output","html");this.a("impl","ifr")};Y.prototype.l=function(){if(!this.I())return;o(window._GA_googleAdData.toString())};Y.prototype.L=function(a){var b;if(this.r){this.h(g);b=this.b+"&currentslot="+u(a)}else b=this.h(a);return b};
Y.prototype.n=function(a){var b=window._GA_googleAdData.s(a);if(b==g){q("This slot has not been defined: "+a);return}window._GA_googleAdData.o.push(a);if(this.v)p("Skip Issuing fetch ads call for "+a);else{var c=this.L(a);this.K(a,c,g,b._width_,b._height_)}};function Z(a){if(a in $)return $[a];return $[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var $={};function v(){return Z("msie")&&!window.opera}function E(){}E.ASYNC="async";E.SYNC="sync";E.SYNC_SRA="sync_sra";E.FALLBACK="fallback";
E.IFRAME="iframe";
E.mustUseFallback=function(){if(v()){var a=P.getIEVersionNumber();o("IE version "+a);return a<=5}else if(Z("firefox")){var b=navigator.userAgent.indexOf("Firefox")+8,c=parseInt(navigator.userAgent.charAt(b),10),d=navigator.userAgent.slice(b);o("FireFox version = "+d+", major= "+c);return c<1}else if(Z("safari")){var b=navigator.userAgent.indexOf("Safari")+7,d=navigator.userAgent.slice(b),f=parseInt(d,10);o("Safari version = "+d+", build="+f);return f<412}else if(window.opera!=g){var b=navigator.userAgent.indexOf("Opera")+
6,d=navigator.userAgent.slice(b),c=parseInt(d,10);o("Opera version = "+d+", major="+c);o("returning "+(c<9));return c<9}else if(!v()&&!Z("safari")&&Z("mozilla")){var b=navigator.userAgent.indexOf("Netscape")+9,d=navigator.userAgent.slice(b),c=parseInt(d,10);o("Netscape version = "+d+", major="+c);return c<7}else return h};
E.canUseAsync=function(){if(v()){var a=P.getIEVersionNumber();o("IE version "+a);return a>5}else if(Z("firefox")){var b=navigator.userAgent.indexOf("Firefox")+8,c=parseInt(navigator.userAgent.charAt(b),10),d=navigator.userAgent.slice(b);o("FireFox version = "+d+", major= "+c);return c>1}return e};E.defaultImpl=function(){if(E.mustUseFallback())return E.FALLBACK;else if(window.google_delayFetch&&E.canUseAsync())return E.ASYNC;return E.SYNC};
E.newInstance=function(a){var b=g;if(typeof a!="undefined"&&a!=g)b=a;else{b=G.getParameter("google_ad_impl");if(b==g)b=E.defaultImpl()}switch(b){case E.ASYNC:o("Using Multiple Call, Asynchronous Implementation");return new R(e);case E.SYNC:o("Using Multiple Call, Synchronous Implementation");return new Q(e);case E.SYNC_SRA:o("Using Single Call, Synchronous Implementation");return new Q(h);case E.FALLBACK:o("Using Multiple Call, Asynchronous Implementation");return new X(e);case E.IFRAME:o("Using Iframe Implementation");
return new Y(e);default:p("unknown implementation ignored, using fallback: "+b);return new X(e)}};o("google_ads.js finished loading");
})()
