// This file is generated by omniidl (C++ backend)- omniORB_4_0. Do not edit.

#include "dtsubject.h"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_0;



dt::DtSubject_ptr dt::DtSubject_Helper::_nil() {
  return ::dt::DtSubject::_nil();
}

CORBA::Boolean dt::DtSubject_Helper::is_nil(::dt::DtSubject_ptr p) {
  return CORBA::is_nil(p);

}

void dt::DtSubject_Helper::release(::dt::DtSubject_ptr p) {
  CORBA::release(p);
}

void dt::DtSubject_Helper::duplicate(::dt::DtSubject_ptr p) {
  if( p && !p->_NP_is_nil() )  omni::duplicateObjRef(p);
}

void dt::DtSubject_Helper::marshalObjRef(::dt::DtSubject_ptr obj, cdrStream& s) {
  ::dt::DtSubject::_marshalObjRef(obj, s);
}

dt::DtSubject_ptr dt::DtSubject_Helper::unmarshalObjRef(cdrStream& s) {
  return ::dt::DtSubject::_unmarshalObjRef(s);
}

dt::DtSubject_ptr
dt::DtSubject::_duplicate(::dt::DtSubject_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);

  return obj;
}


dt::DtSubject_ptr
dt::DtSubject::_narrow(CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


dt::DtSubject_ptr
dt::DtSubject::_unchecked_narrow(CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}


dt::DtSubject_ptr
dt::DtSubject::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_DtSubject _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_DtSubject* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_DtSubject;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* dt::DtSubject::_PD_repoId = "IDL:dt/DtSubject:1.0";


typedef tweek::Subject tweek_Subject;
typedef tweek::_impl_Subject tweek__impl_Subject;
typedef tweek::_objref_Subject tweek__objref_Subject;

dt::_objref_DtSubject::~_objref_DtSubject() {}


dt::_objref_DtSubject::_objref_DtSubject(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::dt::DtSubject::_PD_repoId, ior, id, 1),
   tweek__objref_Subject(ior, id)
   
{
  _PR_setobj(this);
}

void*
dt::_objref_DtSubject::_ptrToObjRef(const char* id)
{
  if( id == ::dt::DtSubject::_PD_repoId )
    return (::dt::DtSubject_ptr) this;
  if( id == ::tweek::Subject::_PD_repoId )
    return (::tweek::Subject_ptr) this;


  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::dt::DtSubject::_PD_repoId) )
    return (::dt::DtSubject_ptr) this;
  if( omni::strMatch(id, ::tweek::Subject::_PD_repoId) )
    return (::tweek::Subject_ptr) this;


  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  void_i_cstring_i_cstring_i_cstring_i_cstring_i_cboolean_i_clong
class _0RL_cd_00EBB0F1982CF9DB_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_00EBB0F1982CF9DB_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall) {}
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  CORBA::String_var arg_0_;
  const char* arg_0;
  CORBA::String_var arg_1_;
  const char* arg_1;
  CORBA::String_var arg_2_;
  const char* arg_2;
  CORBA::String_var arg_3_;
  const char* arg_3;
  CORBA::Boolean arg_4;
  CORBA::Long arg_5;
};

void _0RL_cd_00EBB0F1982CF9DB_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);
  _n.marshalString(arg_2,0);
  _n.marshalString(arg_3,0);
  _n.marshalBoolean(arg_4);
  arg_5 >>= _n;

}

void _0RL_cd_00EBB0F1982CF9DB_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  arg_2_ = _n.unmarshalString(0);
  arg_2 = arg_2_.in();
  arg_3_ = _n.unmarshalString(0);
  arg_3 = arg_3_.in();
  arg_4 = _n.unmarshalBoolean();
  (CORBA::Long&)arg_5 <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_00EBB0F1982CF9DB_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_00EBB0F1982CF9DB_00000000* tcd = (_0RL_cd_00EBB0F1982CF9DB_00000000*)cd;
  dt::_impl_DtSubject* impl = (dt::_impl_DtSubject*) svnt->_ptrToInterface(dt::DtSubject::_PD_repoId);
  impl->setCommand(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3, tcd->arg_4, tcd->arg_5);


}

void dt::_objref_DtSubject::setCommand(const char* identifier, const char* entity, const char* state_attribute, const char* modifier_string, CORBA::Boolean modifier_boolean, CORBA::Long modifier_long)
{
  _0RL_cd_00EBB0F1982CF9DB_00000000 _call_desc(_0RL_lcfn_00EBB0F1982CF9DB_10000000, "setCommand", 11);
  _call_desc.arg_0 = identifier;
  _call_desc.arg_1 = entity;
  _call_desc.arg_2 = state_attribute;
  _call_desc.arg_3 = modifier_string;
  _call_desc.arg_4 = modifier_boolean;
  _call_desc.arg_5 = modifier_long;

  _invoke(_call_desc);



}
dt::_pof_DtSubject::~_pof_DtSubject() {}


omniObjRef*
dt::_pof_DtSubject::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::dt::_objref_DtSubject(ior, id);
}


CORBA::Boolean
dt::_pof_DtSubject::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::dt::DtSubject::_PD_repoId) )
    return 1;
  if( omni::ptrStrMatch(id, tweek::Subject::_PD_repoId) )
    return 1;


  return 0;
}

const dt::_pof_DtSubject _the_pof_dt_mDtSubject;

dt::_impl_DtSubject::~_impl_DtSubject() {}


CORBA::Boolean
dt::_impl_DtSubject::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "setCommand") ) {

    _0RL_cd_00EBB0F1982CF9DB_00000000 _call_desc(_0RL_lcfn_00EBB0F1982CF9DB_10000000, "setCommand", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  
#ifndef _MSC_VER
  if( tweek__impl_Subject::_dispatch(_handle) ) {
    return 1;
  }
#else
  // Work-around for incorrect MSVC code generation.
  if( ((tweek__impl_Subject*)this)->
      tweek__impl_Subject::_dispatch(_handle) ) {
    return 1;
  }
#endif


  return 0;
}

void*
dt::_impl_DtSubject::_ptrToInterface(const char* id)
{
  if( id == ::dt::DtSubject::_PD_repoId )
    return (::dt::_impl_DtSubject*) this;
  if( id == ::tweek::Subject::_PD_repoId )
    return (::tweek::_impl_Subject*) this;


  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::dt::DtSubject::_PD_repoId) )
    return (::dt::_impl_DtSubject*) this;
  if( omni::strMatch(id, ::tweek::Subject::_PD_repoId) )
    return (::tweek::_impl_Subject*) this;


  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
dt::_impl_DtSubject::_mostDerivedRepoId()
{
  return ::dt::DtSubject::_PD_repoId;
}

POA_dt::DtSubject::~DtSubject() {}

